import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { formatDate, formatCurrency } from '@/lib/utils'

const PRIMARY = [79, 70, 229] as [number, number, number]   // indigo-600
const LIGHT   = [238, 242, 255] as [number, number, number] // indigo-50
const DARK    = [30, 27, 75] as [number, number, number]    // indigo-950

function addHeader(doc: jsPDF, title: string, subtitle?: string) {
  // Background bar
  doc.setFillColor(...PRIMARY)
  doc.rect(0, 0, 210, 22, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('School Management System', 14, 10)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text(new Date().toLocaleDateString('en-GB'), 196, 10, { align: 'right' })

  // Title
  doc.setTextColor(...DARK)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text(title, 14, 34)
  if (subtitle) {
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(100, 100, 120)
    doc.text(subtitle, 14, 41)
  }
}

function addFooter(doc: jsPDF) {
  const pages = doc.getNumberOfPages()
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 160)
    doc.text(`Page ${i} of ${pages}`, 196, 287, { align: 'right' })
    doc.text('Generated by School Management System', 14, 287)
    doc.setDrawColor(...PRIMARY)
    doc.setLineWidth(0.3)
    doc.line(14, 283, 196, 283)
  }
}

// ─── Students PDF ────────────────────────────────────────────────
export function exportStudentsPDF(students: any[]): Uint8Array {
  const doc = new jsPDF()
  addHeader(doc, 'Student List', `Total: ${students.length} students`)

  autoTable(doc, {
    startY: 48,
    head: [['#', 'Code', 'Full Name', 'Gender', 'Phone', 'Register Date', 'Status']],
    body: students.map((s, i) => [
      i + 1,
      s.studentCode,
      s.fullName,
      s.gender,
      s.phone || '-',
      formatDate(s.registerDate),
      s.isActive ? 'Active' : 'Inactive',
    ]),
    headStyles: { fillColor: PRIMARY, fontSize: 9, fontStyle: 'bold' },
    bodyStyles: { fontSize: 8.5 },
    alternateRowStyles: { fillColor: LIGHT },
    columnStyles: { 0: { cellWidth: 8 }, 1: { cellWidth: 22 }, 6: { cellWidth: 18 } },
    margin: { left: 14, right: 14 },
  })

  addFooter(doc)
  return doc.output('arraybuffer') as unknown as Uint8Array
}

// ─── Financial Report PDF ────────────────────────────────────────
export function exportFinancialPDF(invoices: any[], period: string): Uint8Array {
  const doc = new jsPDF()
  addHeader(doc, 'Financial Report', period)

  let totalFee = 0, totalPaid = 0, totalDue = 0
  const rows = invoices.map((inv, i) => {
    totalFee  += Number(inv.finalAmount)
    totalPaid += Number(inv.paidAmount)
    totalDue  += Number(inv.dueAmount)
    return [
      i + 1,
      inv.invoiceNo,
      inv.enrollment?.student?.fullName || '',
      inv.enrollment?.course?.name || '',
      formatDate(inv.invoiceDate),
      formatCurrency(Number(inv.finalAmount)),
      formatCurrency(Number(inv.paidAmount)),
      formatCurrency(Number(inv.dueAmount)),
      inv.status,
    ]
  })

  autoTable(doc, {
    startY: 48,
    head: [['#', 'Invoice', 'Student', 'Course', 'Date', 'Total', 'Paid', 'Due', 'Status']],
    body: rows,
    foot: [['', '', '', '', 'TOTAL', formatCurrency(totalFee), formatCurrency(totalPaid), formatCurrency(totalDue), '']],
    headStyles: { fillColor: PRIMARY, fontSize: 8, fontStyle: 'bold' },
    footStyles: { fillColor: [30,27,75], textColor: [255,255,255], fontStyle: 'bold', fontSize: 8 },
    bodyStyles: { fontSize: 7.5 },
    alternateRowStyles: { fillColor: LIGHT },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 8) {
        const val = data.cell.raw as string
        data.cell.styles.textColor =
          val === 'PAID' ? [22, 101, 52] : val === 'PARTIAL' ? [133, 77, 14] : [153, 27, 27]
      }
    },
    margin: { left: 14, right: 14 },
  })

  addFooter(doc)
  return doc.output('arraybuffer') as unknown as Uint8Array
}

// ─── Invoice PDF ─────────────────────────────────────────────────
export function exportInvoicePDF(invoice: any): Uint8Array {
  const doc = new jsPDF()
  const enrollment = invoice.enrollment
  const student = enrollment?.student
  const course = enrollment?.course

  // Header
  doc.setFillColor(...PRIMARY)
  doc.rect(0, 0, 210, 28, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text('INVOICE', 14, 14)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(invoice.invoiceNo, 14, 22)
  doc.setFontSize(9)
  doc.text(formatDate(invoice.invoiceDate), 196, 14, { align: 'right' })

  const statusColors: Record<string, [number, number, number]> = {
    PAID: [22, 101, 52], PARTIAL: [133, 77, 14], UNPAID: [153, 27, 27],
  }
  doc.setTextColor(...(statusColors[invoice.status] || [0,0,0]))
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text(invoice.status, 196, 22, { align: 'right' })

  // Student info box
  doc.setTextColor(...DARK)
  doc.setDrawColor(...PRIMARY)
  doc.setLineWidth(0.4)
  doc.roundedRect(14, 36, 85, 36, 2, 2, 'S')
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(100, 100, 120)
  doc.text('BILL TO', 18, 43)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(...DARK)
  doc.text(student?.fullName || '', 18, 50)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8.5)
  doc.text(`Code: ${student?.studentCode || ''}`, 18, 57)
  doc.text(`Phone: ${student?.phone || '-'}`, 18, 63)

  // Course info box
  doc.roundedRect(109, 36, 87, 36, 2, 2, 'S')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(100, 100, 120)
  doc.text('COURSE INFO', 113, 43)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(...DARK)
  doc.text(course?.name || '', 113, 50)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8.5)
  doc.text(`Class: ${enrollment?.class?.className || ''}`, 113, 57)
  doc.text(`Period: ${formatDate(enrollment?.startDate)} – ${formatDate(enrollment?.endDate)}`, 113, 63)

  // Fee breakdown
  autoTable(doc, {
    startY: 80,
    head: [['Description', 'Amount']],
    body: [
      ['Course Fee', formatCurrency(Number(invoice.totalFee))],
      ['Discount', `- ${formatCurrency(Number(invoice.discount))}`],
      ['Total Amount', formatCurrency(Number(invoice.finalAmount))],
    ],
    foot: [
      ['Paid Amount', formatCurrency(Number(invoice.paidAmount))],
      ['Due Amount', formatCurrency(Number(invoice.dueAmount))],
    ],
    headStyles: { fillColor: PRIMARY, fontSize: 9 },
    footStyles: { fillColor: [30,27,75], textColor: [255,255,255], fontStyle: 'bold' },
    bodyStyles: { fontSize: 9 },
    columnStyles: { 1: { halign: 'right' } },
    margin: { left: 14, right: 14 },
  })

  // Payment history
  if (invoice.payments?.length > 0) {
    const finalY = (doc as any).lastAutoTable.finalY + 10
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(10)
    doc.text('Payment History', 14, finalY)
    autoTable(doc, {
      startY: finalY + 4,
      head: [['Date', 'Amount', 'Method', 'Note']],
      body: invoice.payments.map((p: any) => [
        formatDate(p.paymentDate),
        formatCurrency(Number(p.amount)),
        p.paymentMethod,
        p.note || '',
      ]),
      headStyles: { fillColor: [99, 102, 241], fontSize: 8 },
      bodyStyles: { fontSize: 8.5 },
      alternateRowStyles: { fillColor: LIGHT },
      margin: { left: 14, right: 14 },
    })
  }

  addFooter(doc)
  return doc.output('arraybuffer') as unknown as Uint8Array
}

// ─── Attendance PDF ──────────────────────────────────────────────
export function exportAttendancePDF(records: any[], className: string): Uint8Array {
  const doc = new jsPDF()
  addHeader(doc, 'Attendance Report', className)

  const present = records.filter(r => r.status === 'PRESENT').length
  const absent  = records.filter(r => r.status === 'ABSENT').length
  const late    = records.filter(r => r.status === 'LATE').length

  doc.setFontSize(9)
  doc.setTextColor(60, 60, 80)
  doc.text(`Present: ${present}   Absent: ${absent}   Late: ${late}   Total: ${records.length}`, 14, 45)

  autoTable(doc, {
    startY: 52,
    head: [['#', 'Code', 'Full Name', 'Date', 'Status', 'Note']],
    body: records.map((r, i) => [
      i + 1,
      r.student?.studentCode || '',
      r.student?.fullName || '',
      formatDate(r.attendanceDate),
      r.status,
      r.note || '',
    ]),
    headStyles: { fillColor: PRIMARY, fontSize: 9 },
    bodyStyles: { fontSize: 8.5 },
    alternateRowStyles: { fillColor: LIGHT },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 4) {
        const val = data.cell.raw as string
        data.cell.styles.textColor =
          val === 'PRESENT' ? [22, 101, 52] : val === 'LATE' ? [133, 77, 14] : [153, 27, 27]
        data.cell.styles.fontStyle = 'bold'
      }
    },
    margin: { left: 14, right: 14 },
  })

  addFooter(doc)
  return doc.output('arraybuffer') as unknown as Uint8Array
}
